version: '3'

services:
  config-server:
    image: config-server:dev
    container_name: config-server
    ports:
      - "8888:8888"
  discovery-server:
    image: discovery-server:dev
    container_name: discovery-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    entrypoint: ["./dockerize",  "-wait=tcp://config-server:8888",  "-timeout=120s", "--", "java", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
  admin-server:
    image: admin-server:dev
    container_name: admin-server
    ports:
      - "9090:9090"
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["./dockerize",  "-wait=tcp://discovery-server:8761",  "-timeout=120s", "--", "java", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
  api-gateway:
    image: api-gateway:dev
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["./dockerize",  "-wait=tcp://discovery-server:8761",  "-timeout=120s", "--", "java", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
  customers-server:
    image: customers-server:dev
    container_name: customers-server
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["./dockerize",  "-wait=tcp://discovery-server:8761",  "-timeout=120s", "--", "java", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
  hystrix-dashboard:
    image: hystrix-dashboard:dev
    container_name: hystrix-dashboard
    ports:
      - "7979:7979"
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["./dockerize",  "-wait=tcp://discovery-server:8761",  "-timeout=120s", "--", "java", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
  vets-service:
    image: vets-service:dev
    container_name: vets-service
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["./dockerize",  "-wait=tcp://discovery-server:8761",  "-timeout=120s", "--", "java", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
  visits-service:
    image: visits-service:dev
    container_name: visits-service
    ports:
      - "8083:8083"
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["./dockerize",  "-wait=tcp://discovery-server:8761",  "-timeout=120s", "--", "java", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
  tracing-server:
    image: openzipkin/zipkin
    container_name: tracing-server
    ports:
      - "9411:9411"
  grafana-server:
    image: grafana-server:dev
    container_name: grafana-server
    ports:
      - "3000:3000"
  prometheus-server:
    image: prometheus-server:dev
    container_name: prometheus-server
    ports:
      - "9091:9090"
  mysql-server:
    image: mysql:5.7.8
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: petclinic
      MYSQL_DATABASE: petclinic
    ports:
      - "3306:3306"